version: "3.9"

networks:
  batch-energy-monitoring:
    name: batch-energy-monitoring # Nombre explícito para la red

volumes:
  data_raw:
    driver: local
  data_clean:
    driver: local

services:
  postgres:
    networks:
      - batch-energy-monitoring
    build: ./db
    restart: always
    container_name: postgres   
    ports:
      - "5432:5432"
    environment:
      - bind-address=0.0.0.0
      - POSTGRESQL_DATABASE=batch_energy_monitoring
      - POSTGRESQL_USERNAME=energyuser
      - POSTGRESQL_PASSWORD=energypass
  spark-master:
    networks:
      - batch-energy-monitoring
    build:
      context: .
      dockerfile: spark_jobs/Dockerfile
    container_name: spark-master
    volumes:
      - ./spark_jobs:/app
      - data_raw:/app/data/raw
      - data_clean:/app/data/clean
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
  spark-worker:
    networks:
      - batch-energy-monitoring
    build:
      context: .
      dockerfile: scripts/Dockerfile
    container_name: spark-worker
    depends_on:
      - spark-master
      - postgres
    volumes:
      - ./scripts:/app
      - data_clean:/app/data/clean
      - ./scripts/postgresql-42.7.5.jar:/opt/spark/jars/postgresql-42.7.5.jar
    environment:
      - SPARK_MODE=worker

  simulate:
    networks:
      - batch-energy-monitoring
    build:
      context: .
      dockerfile: simulate/Dockerfile
    container_name: simulate
    volumes:
      - ./simulate:/app
      - data_raw:/app/data/raw
      - data_clean:/app/data/clean
